const array = [
    {
        key:1,
        name:"Deadpool",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"25915.jpg"
    },
    {
        key:2,
        name:"IT",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"37943.jpg"
    },
    {
        key:3,
        name:"Black Panther",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"37945.jpg"
    },
    {
        key:4,
        name:"Assassin",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"329624.jpg"
    }

];
const arrayTwo=[
    {
        key:5,
        name:"Justice League",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"329653.jpg"
    },
    {
        key:6,
        name:"Tron",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"329760.jpg"
    },
    {
        key:7,
        name:"Peres",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"522304.jpg"
    },
    {
        key:8,
        name:"Mad Max",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"681619.jpg"
    },
]
const arrayThree = [
    {
        key:9,
        name:"Bridge",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"681626.jpg"
    },
    {
        key:10,
        name:"Hellboy",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"681688.jpg"
    },
    {
        key:11,
        name:"Transformers",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"681743.jpg"
    },
    {
        key:12,
        name:"Peres",
        type:"Movies",
        Year:"2024",
        quality:"HD",
        img:"681818.jpg"
    }

]
export {array,arrayTwo,arrayThree};